<h3>Terms and Conditions of Service</h3>
<p>These Terms and Conditions of Service ("<strong>Agreement</strong>") are a binding agreement between you ("<strong>you</strong>" or "<strong>your</strong>") and Mostly Serious, LLC ("<strong>Company</strong>" "<strong>us</strong>" "<strong>our</strong>" "<strong>we</strong>") and governs your access and use of Promptly™ (the "<strong>Service</strong>"). You means any individual or entity that uses our Services. If you are entering into this Agreement on behalf of another person or entity, then you represent and warrant that you are authorized to accept the terms of this Agreement on that person or entity’s behalf, in which case, “you” or “your” shall refer to such entity or other person. BY ACCESSING AND USING OUR SERVICE YOU: (A) ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTAND THIS AGREEMENT; (B) REPRESENT THAT YOU ARE 18 YEARS OF AGE OR OLDER; AND (C) ACCEPT THIS AGREEMENT AND AGREE THAT YOU ARE LEGALLY BOUND BY ITS TERMS. IF YOU DO NOT AGREE TO THE TERMS OF THIS AGREEMENT, DO NOT ACCESS OR USE THE SERVICES. THESE TERMS INCLUDE a class action waiver, jury trial waiver, and binding arbitration provision to resolve disputes. Please review carefully.</p>
<ol>
    <li>
        <p><u>Access and Use.</u> Subject to the terms of this Agreement, Company grants you a limited, non-exclusive, and nontransferable license to use the Services strictly in accordance with this Agreement. You acknowledge and agree that the Services are provided under license, and are not sold to you. Except for the limited license rights granted under this Agreement, you do not acquire any ownership interest in the Services under this Agreement, and all rights, title, and interests in the Services will remain with Company and its licensors and service providers, including all copyrights, trademarks, and other intellectual property rights therein or relating thereto. You acknowledge and agree that at times the Services may be inaccessible or inoperable for any reason whatsoever, including, without limitation: (a) equipment malfunctions; (b) periodic maintenance procedures or repairs which Company may undertake from time to time without notice to you; or (c) causes which are beyond the control of Company or which are not reasonably foreseeable. You alone are responsible for your activities and interaction with the Services and represent and warrant to, at all times, use the Services in compliance with applicable law.</p>
    </li>
    <li>
        <p><u>License Restrictions.</u> You shall not: (a) copy the Services, except as expressly permitted by this license; (b) modify, translate, adapt, or otherwise create derivative works or improvements, whether or not patentable, of the Services; (c) reverse engineer, disassemble, decompile, decode, or otherwise attempt to derive or gain access to the source code of the Services or any part thereof; (d) remove, delete, alter, or obscure any trademarks or any copyright, trademark, patent, or other intellectual property or proprietary rights notices from the Services, including any copy thereof; (e) rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer, or otherwise make available the Services, or any features or functionality of the Services, to any third party for any reason; (f) remove, disable, circumvent, or otherwise create or implement any workaround to any copy protection, rights management, or security features in or protecting the Services; (g) use the Services to publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, obscene, indecent or unlawful topic, name, material or information; (h) upload files that contain viruses, Trojan horses, worms, time bombs, cancel bots, corrupted files, or any other similar software or programs that may damage the operation of a computer or property; (i) use the Services in any manner that could damage, disable, overburden, or impair the Company or its Technology Provider (as defined in Section 6) server, or interfere with any other party’s use and enjoyment of the Services. </p>
    </li>
    <li>
        <p><u>Collection and Use of Your Information.</u> You may provide, create, or upload your information while using the Services or certain of its features or functionality, including but not be limited to text, information, photos, data, questions, comments, suggestions, or other content, including personally identifiable information ("<strong>Your Information</strong>"). You will retain ownership rights in Your Information and represent and warrant that Your Information is accurate, complete, up-to-date, and that you have the necessary licenses, rights, consents, and permissions to use and authorize Company to use Your Information in the manner contemplated by this Agreement. By submitting Your Information to Company, you grant Company and our affiliates a worldwide, royalty-free, sub-licenseable, and transferable license to host, store, cache, use, display, reproduce, modify, adapt, edit, publish, prepare derivative works of, analyze, transmit, distribute and otherwise commercial exploit all or any portion of Your Information for any purpose, including, but not limited to operating, developing, providing, promoting, and improving the Services. The license you grant Company under this Section also includes a right for Company to make Your Information available to and pass these rights along to Company’s licensors and service providers with whom Company has a contractual relationship related to the provision of the Services for the purpose of providing the Services. To the extent you provide Company any feedback or suggestions regarding the Services, including, without limitation, new features or functionality related thereto, or any comments, questions, or suggestions, Company is free to use such feedback without any compensation or attribution to you. Further, Your Information is subject to the Company <a href="https://www.mostlyserious.io/privacy-policy" target="_blank">Privacy Policy</a> (the "<strong>Privacy Policy</strong>"). By providing Your Information to or through the Services, you consent to all actions taken by Company with respect to Your Information in compliance with the Privacy Policy.</p>
    </li>
    <li>
        <p><u>Geographic Restrictions.</u> The Services are intended to be used in the United States.  If you access the Services from outside the United States, you are responsible for compliance with all applicable laws to your jurisdiction.</p>
    </li>
    <li>
        <p><u>Updates.</u> Company may from time to time in its sole discretion develop and provide Service updates, which may include upgrades, bug fixes, patches, other error corrections, and/or new features (collectively, including related documentation, "<strong>Updates</strong>"). Updates may also modify or delete in their entirety certain features and functionality. You agree that Company has no obligation to provide any Updates or to continue to provide or enable any particular features or functionality. You shall promptly download and install all Updates and acknowledge and agree that the Services or portions thereof may not properly operate should you fail to do so. You further agree that all Updates will be deemed part of the Services and be subject to all terms and conditions of this Agreement.</p>
    </li>
    <li>
        <p><u>Additional Terms and Services.</u>  You knowledge and agree that Company uses or relies on technology provided by third party service provider to provide some portions of the Service, including but not limited to Pixel & Tonic, Inc. and OpenAI, LLC ("<strong>Technology Partners</strong>"), and that the operation, availability, and use of the Services is contingent on such Technology Partners. By using the Service, you also agree to be bound by the Pixel & Tonic Terms of Use and the OpenAI, L.L.C. terms of use ("<strong>OpenAI</strong>"), or any other Technology Provider terms linked to the Services, which shall be incorporated herein by reference. To the extent there is a conflict between the terms of this Agreement and the terms of the Technology Provider, the terms of this Agreement shall control for the Service and the terms of the Technology Provider terms shall control for the Technology Provider Services (as defined below). Furthermore, in order to receive the Services, you acknowledge and agree that you are required to open and maintain an account with OpenAI directly and pay any associated fees associated therewith, which are in addition to any service fees for the Services hereunder this Agreement.  You acknowledge and agree Company is not responsible for the failure to provide the Services, if such failure is a result of or arising out of your failure to maintain an OpenAI account or comply with the OpenAI terms of use, or the terms of use of any other Technology Provider. Further, Company shall have no liability for the services or materials provided by the Technology Providers, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality, or any other aspect thereof ("<strong>Technology Provider Services</strong>").</p>
    </li>
    <li>
        <p><u>Fees, Payments, Automatic Renewals.</u>  By using the Service, you agree to pay us the fees specified in the online plugin store using the payment information you provide. You authorize Craft to store your payment information and agree to update your payment information as may be necessary to ensure uninterrupted services (e.g. related to subscription renewals).  If your payment fails for any reason, we may immediately cancel or revoke your access to the Services without notice to you.  All Service fees are exclusive of any applicable federal, state, local or other governmental sales taxes ("<strong>Taxes</strong>"). You are responsible for paying all applicable Taxes related to the use of our Services. Your subscription to the Service begins on your date of purchase and you authorize us to automatically charge you the applicable renewal fees and taxes for each subscription period until you cancel your subscription. You may cancel your subscription at any time by contracting us, but not later than at least one month before the scheduled end date of your annual subscription to avoid automatic renewal. See Section 8 below for more information about termination of Services.  All fees paid for the Services are nonrefundable and payments are final. We do not offer refunds. We may change our fees at any time.  Any renewal of your subscription will be at our then-current pricing.  If you don’t agree to the changes, you must cancel your Service. </p>
    </li>
    <li>
        <p><u>Termination.</u> Company may terminate your access to the Services by providing you at least one month notice before the expiration of your subscription. This termination will only affect your ability to receive updates to the Services, and unless you have violated another provision of this Agreement, you will continue to have access to the version of the Services that you originally purchased.  Company may terminate this Agreement and your access to the Services at any time without notice to you if you violate any of the terms and conditions of this Agreement. Upon termination: (a) all rights granted to you under this Agreement will also terminate, including, but not limited any license rights set forth in Section 1 of this Agreement; and (b) you must cease all use of the Services. Termination will not limit any of Company's rights or remedies at law or in equity and any provisions of this Agreement that by its terms has application to events following termination shall remain in full force and effect.</p>
    </li>
    <li>
        <p><u>General Disclaimers.</u> THE SERVICES ARE PROVIDED TO YOU "AS IS" AND WITH ALL FAULTS AND DEFECTS WITHOUT WARRANTY OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, COMPANY, ON ITS OWN BEHALF AND ON BEHALF OF ITS AFFILIATES AND ITS AND THEIR RESPECTIVE LICENSORS AND SERVICE PROVIDERS, EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO THE SERVICES, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, AND WARRANTIES THAT MAY ARISE OUT OF COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE, OR TRADE PRACTICE. WITHOUT LIMITATION TO THE FOREGOING, COMPANY PROVIDES NO WARRANTY OR UNDERTAKING, AND MAKES NO REPRESENTATION OF ANY KIND THAT THE SERVICE WILL MEET YOUR REQUIREMENTS, ACHIEVE ANY INTENDED RESULTS, BE COMPATIBLE, OR WORK WITH ANY OTHER SOFTWARE, APPLICATIONS, SYSTEMS, OR SERVICES, OPERATE WITHOUT INTERRUPTION, MEET ANY PERFORMANCE OR RELIABILITY STANDARDS, OR BE ERROR-FREE, OR THAT ANY ERRORS OR DEFECTS CAN OR WILL BE CORRECTED. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF OR LIMITATIONS ON IMPLIED WARRANTIES OR THE LIMITATIONS ON THE APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO SOME OR ALL OF THE ABOVE EXCLUSIONS AND LIMITATIONS MAY NOT APPLY TO YOU.</p>
    </li>
    <li>
        <p><u>Output Disclaimers.</u> You acknowledge and agree that any content created by openai in connection with the Services ("<strong>Output</strong>") may not copyrightable under applicable law and use of the Output is at your sole risk and liability.  You understand that the Output may be inaccurate, and we make no representation or warranty as to the accuracy, completeness of the Output, including, but not limited to whether the Output has the necessary licenses, rights, consents, and permissions to use any information it obtained to create the Output.</p>
    </li>
    <li>
        <p><u>Limitation of Liability.</u> TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL COMPANY OR ITS AFFILIATES, OR ANY OF ITS OR THEIR RESPECTIVE LICENSORS OR SERVICE PROVIDERS, HAVE ANY LIABILITY ARISING FROM OR RELATED TO YOUR USE OF OR INABILITY TO USE THE SERVICES FOR (A) PERSONAL INJURY, PROPERTY DAMAGE, LOST PROFITS, COST OF SUBSTITUTE GOODS OR SERVICES, LOSS OF DATA, LOSS OF GOODWILL, BUSINESS INTERRUPTION, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, SPECIAL, OR PUNITIVE DAMAGES; OR (B) DIRECT DAMAGES IN AMOUNTS THAT IN THE AGGREGATE EXCEED THE AMOUNT ACTUALLY PAID BY YOU FOR THE SERVICES. THE FOREGOING LIMITATIONS WILL APPLY WHETHER SUCH DAMAGES ARISE OUT OF BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE AND REGARDLESS OF WHETHER SUCH DAMAGES WERE FORESEEABLE OR COMPANY WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS OF LIABILITY SO SOME OR ALL OF THE ABOVE LIMITATIONS OF LIABILITY MAY NOT APPLY TO YOU. THE MAXIMUM LIABILITY FOR THE COMPANY UNDER THIS AGREEMENT OR ANY ASSOCIATED OR RELATED CLAIMS SHALL BE LIMITED TO THE AMOUNTS YOU HAVE PAID THE COMPANY WITHIN THE PRIOR SIX (6) MONTHS OF WHEN YOUR CLAIM ACCRUED.</p>
    </li>
    <li>
        <p><u>Indemnification.</u> You agree to indemnify, defend, and hold harmless Company and its officers, directors, employees, agents, affiliates, successors, and assigns from and against any and all losses, damages, liabilities, deficiencies, claims, actions, judgments, settlements, interest, awards, penalties, fines, costs, or expenses of whatever kind, including attorneys' fees, arising from or relating to: (a) your use or misuse of the Services; (b) your breach of this Agreement; (c) use of Your Information, including infringement claims, or any data or results derived therefrom in your use of the Services; (d) your breach of any Technology Provider terms and conditions; and (e) your use of the Outputs. </p>
    </li>
    <li>
        <p><u>Export Regulation.</u> The Services may be subject to United States export control laws, including the Export Control Reform Act and its associated regulations. You shall not, directly or indirectly, export, re-export, or release the Services to, or make the Services accessible from, any jurisdiction or country to which export, re-export, or release is prohibited by law, rule, or regulation. You shall comply with all applicable federal laws, regulations, and rules, and complete all required undertakings (including obtaining any necessary export license or other governmental approval), prior to exporting, re-exporting, releasing, or otherwise making the Service available outside the United States.</p>
    </li>
    <li>
        <p><u>Severability.</u> If any provision of this Agreement is illegal or unenforceable under applicable law, the remainder of the provision will be amended to achieve as closely as possible the effect of the original term and all other provisions of this Agreement will continue in full force and effect.</p>
    </li>
    <li>
        <p><u>Dispute Resolution Procedures.</u> If you believe we have breached this Agreement or our provision of the Services to you, you agree that as a material provision of this Agreement that you will provide us with a detailed written notice of any claimed deficiencies and at least thirty (30) days to cure such alleged deficiency prior to commencing any arbitration proceeding against us as set forth below. If the Company takes steps to fix the issue, but the fix cannot be completed within the thirty (30) day time period, then the Company shall continue to have the opportunity to fix the issue without you bringing a legal claim so long as the Company uses commercially reasonable means without undue delay to resolve the issue.  During the aforementioned cure periods, any applicable statute of limitations period will be automatically tolled.  If the Company provides written notice to you that it is waiving this Section or otherwise is not pursuing a resolution to your proposed claims, the tolling period shall automatically cease within three (3) days of such notice being provided to you. Should you violate this provision and fail to give us such notice, it shall constitute a material breach of this Agreement and entitle us to all of our attorneys’ fees, court costs, and any related expenses associated with enforcing our right to the thirty (30) day cure period.  This provision specifically applies to any and all claims under local, state or federal law, and specifically includes claims related to the American with Disabilities Act.</p>
    </li>
    <li>
        <p><u>Governing Law and Binding Arbitration.</u> This Agreement is governed by and construed in accordance with the internal laws of the State of Missouri without giving effect to any choice or conflict of law provision or rule. You agree that any claim, dispute, action or litigation based hereon, relating to or arising out of this Agreement, or the Services shall be brought and maintained exclusively via arbitration (except for injunctive relief). Any party seeking to pursue an action to arbitrate shall give written notice to the other party of such election that summarizes in sufficient detail the basis of the dispute at least ten (10) days before bringing an arbitration action. The dispute shall be submitted for arbitration with JAMS in accordance with its Comprehensive Arbitration Rules and Procedures. Such arbitration shall be conducted, unless otherwise agreed by the parties, by a single arbitrator, who shall be a former judge, in Springfield, Missouri. The award of the arbitrator may be confirmed or enforced in any court of competent jurisdiction. The prevailing party in any arbitration shall be entitled to recover all costs incurred by such party in connection with the proceeding, including reasonable attorneys’ fees.  If injunctive relief is needed, the parties agree to exclusively utilize the courts with jurisdiction in Springfield, Missouri. You expressly waive any objection of venue and jurisdiction, including but not limited to arguments that such litigation any action has been brought in an inconvenient forum.</p>
    </li>
    <li>
        <p><u>Limitation of Time to File Claims.</u> WE WISH TO TIMELY RESOLVE ANY DISPUTES THAT YOU MAY HAVE WITH US.  ACCORDINGLY, ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE SERIVCES MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES OTHERWISE SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.</p>
    </li>
    <li>
        <p><u>Waiver of Jury Trial and Class Action.</u> EACH OF THE PARTIES HERETO HEREBY WAIVES ANY RIGHT TO A TRIAL BY JURY IN ANY ACTION OR PROCEEDING TO ENFORCE OR DEFEND ANY RIGHTS UNDER THIS AGREEMENT. FURTHER, EACH OF THE PARTIES HERETO HEREBY WAIVES ANY RIGHT TO PARTICIPATE IN A CLASS ACTION AND INSTEAD, AGREES THAT ANY AND ALL DISPUTES SHALL BE RESOLVED ON AN INDIVIDUAL BASIS. </p>
    </li>
    <li>
        <p><u>Waiver.</u> No failure to exercise, and no delay in exercising, on the part of either party, any right or any power hereunder shall operate as a waiver thereof, nor shall any single or partial exercise of any right or power hereunder preclude further exercise of that or any other right hereunder. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.</p>
    </li>
    <li>
        <p><u>Successors and Assigns.</u> You may not assign any of your rights or delegate any of your duties under this Agreement or the Privacy Policy without Company’s prior written consent. Except as otherwise expressly provided herein, this Agreement shall bind and inure to the benefit of the successors, assigns, heirs, executors and administrators of the parties hereto.</p>
    </li>
    <li>
        <p><u>Changes to this Agreement.</u> From time to time, Company may, in its sole discretion, change, modify, supplement or remove portions of this Agreement. Such changes shall become effective upon the posting of the revised Agreement or upon sending you an email or other notification. You will be deemed to have agreed to such change by continuing to use the Services following the date in which such changes become effective.</p>
    </li>
    <li>
        <p><u>Entire Agreement.</u> This Agreement and our Privacy Policy constitute the entire agreement between you and Company with respect to the Services and supersede all prior or contemporaneous understandings and agreements, whether written or oral, with respect to the Services. </p>
    </li>
</ol>
